### ISSUE TITLE
Bug: unknown flag: --vscode

### ISSUE THREAD

**Issue by qaqland** [owenthereal/upterm#154]
Following this guide [upterm改造(一)-支持VSCode远程连接任意容器](https://corvo.myseu.cn/2022/04/23/2022-04-23-%E6%94%B9%E9%80%A0upterm%E4%BB%A5%E6%94%AF%E6%8C%81VSCode%E8%BF%9C%E7%A8%8B%E8%BF%9E%E6%8E%A5%E4%BB%BB%E6%84%8F%E5%AE%B9%E5%99%A8/) and run:

```bash
bash <(curl -sL http://corvo.myseu.cn/scripts/upterm.sh)
```

Get 
```
unknown flag: --vscode
```

My system is Alpine Linux v3.17 x86_64.

**Comment by corvofeng** [comment]
这个项目是我fork出来改造的了 原项目不支持的.
