### ISSUE TITLE
Distribution-based package formats install binary at the wrong place

### ISSUE THREAD

**Issue by rlko** [owenthereal/upterm#247]
Greetings, first of all thank you for this project, been using a lot at my corpa job.

I just came here to report you that, I think most, if not all of distribution-based package formats (deb, rpm) are installing the binary in a place that does not belong in the default PATH environment variable.

```bash
$ dpkg-deb --contents upterm_linux_amd64.deb
drwxr-xr-x root/root         0 2024-04-17 18:39 ./usr/
-rwxr-xr-x root/root  14704640 2024-04-17 18:38 ./usr/upterm
```

```bash
$ rpm -qlp upterm_linux_amd64.rpm
/usr/upterm
```

I think you meant to place this in `/usr/bin/` and not `/usr`

It's been like this for quite a while ever since you started making deb/rpm releases basically, and I thought you would eventually figure out with time or someone would report it earlier.

**Comment by owenthereal** [comment]
Thanks for reporting this. The fix should be rolled out at the next release.
