### ISSUE TITLE
Tmux fails to start, but only on macOS

### ISSUE THREAD

**Issue by neongreen** [owenthereal/upterm#253]
I'm experiencing a weird issue.

I'm using Upterm to connect to a Github Actions runner (via https://github.com/lhotari/action-upterm).

When SSH-ing to `uptermd.upterm.dev` from a macOS machine, the connection goes through but then immediately exits. With `ssh -vvv`:

```bash
runner@fv-az1521-140:~/work/brick/brick$ debug3: obfuscate_keystroke_timing: starting: interval ~20ms
debug2: channel 1: rcvd adjust 10
debug3: send packet: type 1
debug1: channel 0: free: /Users/artyom/.ssh/171450439924387, nchannels 2
debug3: channel 0: status: The following connections are open:
  #1 client-session (t4 [session] r0 i0/0 o0/0 e[write]/0 fd 8/9/10 sock -1 cc -1 io 0x01/0x00)

debug1: channel 1: free: client-session, nchannels 1
debug3: channel 1: status: The following connections are open:
  #1 client-session (t4 [session] r0 i0/0 o0/0 e[write]/0 fd 8/9/10 sock -1 cc -1 io 0x01/0x00)

Connection to uptermd.upterm.dev closed by remote host.
Connection to uptermd.upterm.dev closed.
Transferred: sent 6204, received 3016 bytes, in 0.6 seconds
Bytes per second: sent 9822.5, received 4775.1
debug1: Exit status -1
```

"work/brick/brick" is a path inside the GitHub runner.

I tried passing `-i ~/.ssh/id_ed25519` to `ssh`, but it changed nothing.

However, when I try the same from a Linux machine, it works fine and I am dropped into tmux.

It used to work just fine on the same machine a while ago (half a year? one year?) so I'm not sure what the problem might be.

**Comment by owenthereal** [comment]
@neongreen You can use my fork for now: https://github.com/owenthereal/action-upterm. I will ensure my changes are contributed upstream. I'm also thinking of creating the official GitHub Actions for upterm myself.

Closing. Feel free to reopen if you run into any issues.
