### ISSUE TITLE
"FLY_APP_NAME is not set" on upgrade

### ISSUE THREAD

**Issue by Jonher937** [owenthereal/upterm#262]
Hi, due to the addition of the fly-wrapper and it being set as the default entrypoint here: https://github.com/owenthereal/upterm/blob/1846c3ac2ee368f0419b7bb805b62d33e1e09ae0/Dockerfile.uptermd#L42 upgrade of upterm fails unless the user overrides the entrypoint.

Easy fix for someone that can figure that out, but would have been great to menton in changelog if it was not defaulted to by accident.

A user can override the entrypoint back to `uptermd` to pass upgrade.

**Comment by owenthereal** [comment]
This is not desired. I fixed it in https://github.com/owenthereal/upterm/pull/263. Please wait for the new release 0.14.3
