### ISSUE TITLE
ControlPath too long ('[...]@uptermd.upterm.dev:22' >= 104 bytes)

### ISSUE THREAD

**Issue by laverdet** [owenthereal/upterm#283]
Hello, this isn't a bug report I just want to document this in case anyone runs into it again. I got this error while trying to use upterm and Google wasn't any help.

```
ControlPath too long ('[...]@uptermd.upterm.dev:22' >= 104 bytes)
```

I got the error on multiple machines I own so I was pretty confused. It turns out that like 14 years ago I added this to my `.ssh/config` file and synced it across my devices:

```
Host *
  ControlPath ~/.ssh/%l-%r@%h:%p
```

This directive shares one ssh connection between multiple invocations to `ssh` to the same host. It's actually pretty nice if you're doing a lot of invocations to `scp` in multiple terminals. Anyway turns out that there's a maximum length on that control path. Uh so if you get this error message that's what's going on.

**Comment by xlambein** [comment]
I'm having the same issue, which is a bit annoying because I'd like to keep my `ControlPath` option in my `.ssh/config`. I'm annoyed that there's this restriction on OpenSSH, but I'm also curious to know why the upterm usernames are so long 😅

**Comment by xlambein** [comment]
Well, for now I found a fix to my issue. Instead of using `%r` in the `ControlPath`, you can use `%C`, which is a hash of several values including `%r`. This fixes the issue.

For example, I use `ControlPath ~/.ssh/master-%C@%n:%p`.
