### ISSUE TITLE
Private key required when ssh-agent already populated

### ISSUE THREAD

**Issue by MichaelBitard** [owenthereal/upterm#73]
Hello, we are trying upterm as an alternative to tmate, and it's seems to be working great, so, first of all, thanks for this project!

On my machine though, I don't have any private key files, they are stored in a safe (KeePassXC) and, when I unlock my safe, my key is added to my ssh-agent.

My workaround for upterm is to create an ssh-key, but I wonder if we could have an option to specify an ssh-agent directly where it could retrieve the keys and the signers.

If you agree with that, I could try and create a PR

**Comment by rothgar** [comment]
Another option from discussions in #72 is maybe we could create temporary public/private keys when running `upterm host`. I'm not sure the client ever cares what the private key from the server to upterm connection host is. Maybe I'm still understanding what the private key is actually used for on the host.

**Comment by owenthereal** [comment]
`upterm` should already read keys from ssh-agent first then fall back to key files: https://github.com/owenthereal/upterm/blob/44f1490d38e01b0901886bdc830816cc0101f652/host/signer.go#L60. Please upgrade to the latest version and let me know if that works

**Comment by rothgar** [comment]
My use case is on temporary hosts that don't have ssh keys or ssh-agent available. In that case it would be great if there were an easier way to create the ssh tunnel connection

**Comment by owenthereal** [comment]
@rothgar upterm starts an sshd server on the host and the ssh keys are used to establish a secured tunnel between the host and the uptermd server: https://github.com/owenthereal/upterm#how-it-works. There are tools like ssh-keygen to generate keys already, are you looking for upterm generating the keys for you instead?

**Comment by rothgar** [comment]
Yes, automatically generating a key (or having a flag to auto generate a key) is what I was thinking. I know users _can_ create ssh keys but in the case that the machine/user doesn't have a key it would be nice to automatically generate a temporary key for the initial tunnel.

This would be especially useful on temporary cloud instances or from inside containers.

**Comment by MichaelBitard** [comment]
The problem is, the `--private-key` argument is mandatory, and I don't have one since my private key is not physically accessible (it's in my keepass2 vault)

**Comment by MichaelBitard** [comment]
Thanks! I'll try this soon!
