### ISSUE TITLE
"upterm upgrade" fails with "no binary for your system"

### ISSUE THREAD

**Issue by larsks** [owenthereal/upterm#94]
I'm running upterm (v0.6.7) locally, and trying to run `upterm upgrade` results in:

```
Error: no binary for your system
Usage:
  upterm upgrade [flags]

Examples:
  # Upgrade to the latest version
  upterm upgrade

  # Upgrade to a specific version
  $ upterm upgrade 0.2.0

Flags:
  -h, --help   help for upgrade

FATA[0000] no binary for your system
```

That's an odd error (it's just a regular amd64 system), and the error message doesn't really provide enough information to be actionable.

**Comment by owenthereal** [comment]
Please refer to https://github.com/owenthereal/upterm/pull/97 for a fix. I will cut a release in a bit. You may need to redownload the `upterm` depending on how you install it.

**Comment by owenthereal** [comment]
https://github.com/owenthereal/upterm/releases/tag/v0.6.8
